# Generated by Django 4.2 on 2023-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("email", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="teachers",
            old_name="email",
            new_name="person",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="age",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="last_name",
        ),
    ]
