# Generated by Django 4.2 on 2023-04-27 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_teacher_rename_email_teachers_person_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teachers",
        ),
    ]
